export const ROUTES_PATH = {
  LAWSUIT_MONITOR: {
    BASE: '/jusprocessos',
    BASE_V2: '/jusprocessos-v2',
    SUBSCRIPTION: '/assinatura',
    LAWSUITS: '/meus-processos',
    DETAILS: '/detalhes',
    DEADLINES: '/prazos',
    COMPLETED_DEADLINES: '/prazos-concluidos',
    CONFIG: '/configuracoes',
    ADICAO_CNJ: '/adicao-cnj',
    DEADLINES_LIST: `/prazos/lista`,
    DEADLINES_CALENDAR: `/prazos/calendario`,
    SETUP_STEPS: '/etapas',
    SETUP: '/inicio',
  },
  JUSZAP: {
    LANDING_PAGE: '/assistente-whatsapp',
    BASE: '/space/whatsapp',
    TEAM_MANAGEMENT: '/space/whatsapp/gerenciamento-equipe',
  },
  GAMIFICATION: {
    BASE: '/gamificacao',
    HISTORICO: '/gamificacao/historico',
  },
  MAIN: {
    DASHBOARD: '/dashboard',
    JUSFINDER_QUERY: '/jusfinder/query',
    ASSINATURAS: '/assinaturas',
    GPT: '/gpt',
  },
  JUSFYPAY: {
    BASE: '/jusfypay/landing',
    FAQ: '/jusfypay/landing/#faq',
    DASHBOARD: '/jusfypay/dashboard',
    PAYMENT_LINKS: '/jusfypay/payment-links',
    NEW_CHARGE: '/jusfypay/new-charge',
    PAYMENTS: '/jusfypay/payments',
    WALLET: '/jusfypay/wallet',
    PROFILE: '/jusfypay/profile',
  },
  SETTINGS: {
    PERFIL: '/perfil',
  },
  PROCESSOS: {
    JUSFINDER_QUERY: '/jusfinder/query',
    HISTORY_BATCH: '/jusfinder/history_batch',
    CALCULADORAS: '/calculadoras',
    PETICOES: '/peticoes',
    MEUS_PROCESSOS: '/jusprocessos/meus-processos',
    PRAZOS: '/jusprocessos/prazos/lista',
    AGENDA: '/agenda',
  },
  CLIENTES: {
    ASSINATURAS: '/assinaturas',
    CLIENTES: '/clientes',
    SPACE_DOMAIN: '/space/domain',
    JUSMAIL_REDIRECT: '/jusmail-redirect',
    OPORTUNIDADES: '/oportunidades',
    PAGE: '/page',
  },
  CONFIGURACOES: {
    PERFIL: '/perfil',
    USUARIOS: '/usuarios',
  },
  EXTERNAL: {
    COMUNIDADE: 'https://comunidade.jusfy.com.br/top?period=monthly',
    MANUALS: 'https://help.jusfy.com.br',
  },
  CALCULADORAS: {
    CALCULOS: '/calculos',
    ATUALIZACAO: '/atualizacao',
    ATUALIZACAO_COMPLETO: '/atualizacao_completo',
    REVISIONAL: '/revisional',
    SUPERENDIVIDAMENTO: '/superendividamento',
    RMC: '/rmc',
    PASEP: '/pasep',
    TRABALHISTA: '/trabalhista',
    FGTS: '/fgts',
    PENSAO: '/pensao',
    ALUGUEL: '/aluguel',
    DIVORCIO: '/divorcio',
    INSS: '/inss',
    PROGRESSAO_REGIME: '/progressao-regime',
    DOSIMETRIA_PENA: '/dosimetria-pena',
    FAMILIAR: '/familiar',
    BANCARIO: '/bancario',
    CONSUMIDOR: '/consumidor',
  },
  CONTABILIDADE: {
    LANDING_PAGE: '/contabilidade',
  },
} as const;

export const CALCULADORAS_PATHS = Object.values(ROUTES_PATH.CALCULADORAS);
export const JUSZAP_PATHS = Object.values(ROUTES_PATH.JUSZAP);
