import {
  Documents,
  ICardOption,
} from '../../../components/CardOptionQuery/types.CardOption';
import { DOCUMENTS_ENUM } from '../../../components/DOCUMENTS_ENUM';

export const OPTIONS = [
  { value: 'CPF', title: 'CPF' },
  { value: 'CNPJ', title: 'CNPJ' },
  { value: 'PLATE', title: 'Placa' },
];

export const CARD_OPTIONS: ICardOption[] = [
  {
    checked: false,
    feature_type_name: 'household',
    universal_price: 1,
    credits: '1',
    isUniversal: false,
    description:
      'Relação entre empresas com atividades semelhantes em um mesmo endereço',
    text_info_credit: '1 crédito',
    onChange: () => {},
    name_query: 'Grupo econômico (atividade semelhante no endereço)',
    documents: ([DOCUMENTS_ENUM.CNPJ] as unknown) as Documents,
  },
  {
    checked: false,
    feature_type_name: 'household_activity',
    universal_price: 1,
    credits: '1',
    isUniversal: false,
    description:
      'Relação entre empresas com qualquer atividade em um mesmo endereço',
    text_info_credit: '1 crédito',
    onChange: () => {},
    name_query: 'Grupo econômico (qualquer atividade no endereço)',
    documents: ([DOCUMENTS_ENUM.CNPJ] as unknown) as Documents,
  },
  {
    checked: false,
    feature_type_name: 'rfcontact',
    universal_price: 1,
    credits: '1',
    description:
      'Relação entre empresas com o mesmo contato na Receita Federal',
    text_info_credit: '1 crédito',
    onChange: () => {},
    name_query: 'Grupo econômico (mesmo contato na Receita Federal)',
    isUniversal: false,
    documents: ([DOCUMENTS_ENUM.CNPJ] as unknown) as Documents,
  },
  {
    checked: false,
    feature_type_name: 'owners',
    universal_price: 1,
    credits: '1',
    description: 'Relação entre empresas com o mesmo quadro societário',
    text_info_credit: '1 crédito',
    onChange: () => {},
    name_query: 'Grupo econômico (mesmo quadro societário)',
    isUniversal: false,
    documents: ([DOCUMENTS_ENUM.CNPJ] as unknown) as Documents,
  },
  {
    checked: false,
    feature_type_name: 'legal_representative',
    universal_price: 1,
    credits: '1',
    description: 'Relação entre empresas com o mesmo representante legal',
    text_info_credit: '1 crédito',
    onChange: () => {},
    name_query: 'Grupo econômico (mesmo representante legal)',
    isUniversal: false,
    documents: ([DOCUMENTS_ENUM.CNPJ] as unknown) as Documents,
  },
  {
    checked: false,
    feature_type_name: 'trademarks',
    universal_price: 1,
    credits: '1',
    description:
      'Informações e histórico de marcas e patentes relacionadas à pessoa física ou jurídica',
    text_info_credit: '1 crédito',
    onChange: () => {},
    name_query: 'Marcas e patentes',
    isUniversal: false,
    documents: ([
      DOCUMENTS_ENUM.CPF,
      DOCUMENTS_ENUM.CNPJ,
    ] as unknown) as Documents,
  },
  {
    checked: false,
    feature_type_name: 'lawsuit',
    universal_price: 1,
    credits: '1',
    description:
      'Informações de processos envolvendo a pessoa física ou jurídica',
    text_info_credit: '1 crédito',
    onChange: () => {},
    name_query: 'Processos',
    isUniversal: false,
    documents: ([
      DOCUMENTS_ENUM.CPF,
      DOCUMENTS_ENUM.CNPJ,
    ] as unknown) as Documents,
  },
  {
    checked: false,
    feature_type_name: 'relationship_tree',
    universal_price: 3,
    credits: '3',
    description:
      'Informações de relações familiares e societárias da pessoa física ou jurídica',
    text_info_credit: '3 créditos',
    onChange: () => {},
    name_query: 'Relacionamentos',
    isUniversal: false,
    documents: ([
      DOCUMENTS_ENUM.CPF,
      DOCUMENTS_ENUM.CNPJ,
    ] as unknown) as Documents,
  },

  {
    checked: false,
    feature_type_name: 'company_information',
    universal_price: 3,
    credits: '3',
    description:
      'Informações da pessoa jurídica, incluindo CNAEs e quadro societário',
    text_info_credit: '3 créditos',
    onChange: () => {},
    name_query: 'Dados da empresa',
    isUniversal: false,
    documents: ([DOCUMENTS_ENUM.CNPJ] as unknown) as Documents,
  },
  {
    checked: false,
    feature_type_name: 'cpf_registration_status',
    universal_price: 1,
    credits: '1',
    description:
      'Situação cadastral da pessoa, incluindo óbito, nos registros da Receita Federal',
    text_info_credit: '1 crédito',
    onChange: () => {},
    name_query: 'Situação cadastral',
    isUniversal: false,
    documents: ([DOCUMENTS_ENUM.CPF] as unknown) as Documents,
  },
  {
    checked: false,
    feature_type_name: 'professional_data',
    universal_price: 1,
    credits: '1',
    description:
      'Histórico atualizado de empregos da pessoa física nos registros da Receita Federal e RAIS',
    text_info_credit: '1 crédito',
    onChange: () => {},
    name_query: 'Dados profissionais',
    isUniversal: false,
    documents: ([DOCUMENTS_ENUM.CPF] as unknown) as Documents,
  },
  {
    checked: false,
    feature_type_name: 'personal_data',
    universal_price: 1,
    credits: '1',
    description:
      'Informações para localizar a pessoa, como nome completo, endereço e meios de contato',
    text_info_credit: '1 crédito',
    onChange: () => {},
    name_query: 'Localização',
    isUniversal: false,
    documents: ([DOCUMENTS_ENUM.CPF] as unknown) as Documents,
  },
  {
    checked: false,
    feature_type_name: 'company_partnership',
    universal_price: 1,
    credits: '1',
    description: 'Informações de participações societárias da pessoa física',
    text_info_credit: '3 créditos',
    onChange: () => {},
    name_query: 'Sociedades',
    isUniversal: false,
    documents: ([DOCUMENTS_ENUM.CPF] as unknown) as Documents,
  },
  {
    checked: false,
    feature_type_name: 'credit_restriction',
    universal_price: 3,
    credits: '3',
    description:
      'Informações de crédito de pessoas físicas ou jurídicas em tempo real do Serasa e Boa Vista',
    text_info_credit: '3 créditos',
    onChange: () => {},
    name_query: 'Restrição de crédito',
    isUniversal: false,
    documents: ([
      DOCUMENTS_ENUM.CPF,
      DOCUMENTS_ENUM.CNPJ,
    ] as unknown) as Documents,
  },
  {
    checked: false,
    feature_type_name: 'list_vehicles',
    universal_price: 5,
    credits: '5',
    description:
      'Veículos na base nacional do DETRAN em nome da pessoa física ou jurídica',
    text_info_credit: '5 créditos',
    onChange: () => {},
    name_query: 'Lista de veículos',
    isUniversal: false,
    documents: ([
      DOCUMENTS_ENUM.CPF,
      DOCUMENTS_ENUM.CNPJ,
    ] as unknown) as Documents,
  },
  {
    checked: false,
    feature_type_name: 'vehicle_data',
    universal_price: 3,
    credits: '3',
    description:
      'Valor da PIFE, marca, modelo, ano, Renavam, combustível, localização e dados do proprietário',
    text_info_credit: '3 créditos',
    onChange: () => {},
    name_query: 'Dados do veículo',
    isUniversal: false,
    documents: ([DOCUMENTS_ENUM.PLATE] as unknown) as Documents,
  },
  {
    checked: false,
    feature_type_name: 'vehicle_tracking',
    universal_price: 5,
    credits: '5',
    description: 'Lista de capturas do veículo com fotos, local, data e hora',
    text_info_credit: '5 créditos',
    onChange: () => {},
    name_query: 'Rastreamento de veículos',
    isUniversal: false,
    documents: ([DOCUMENTS_ENUM.PLATE] as unknown) as Documents,
  },
];

export const STATUS = ['pending', 'error'];
